apiVersion: v1
kind: Service
metadata:
  name: {{ include "user_management_service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ include "user_management_service.name" . }}