apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-management-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "user-management-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "user-management-service.name" . }}
    spec:
      serviceAccountName: eks-apps-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: user-management-config
            - secretRef:
                name: user-management-secrets
