apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      serviceAccountName: eks-apps-service-account
      containers:
        - name: user-management-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: user-management-config
            - secretRef:
                name: user-management-secrets
