apiVersion: v1
kind: Secret
metadata:
  name: user-management-secrets
  labels:
    app: user-management-service
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  LOG_GROUP_MAIN: "your-cloudwatch-log-group"
  STREAM_NAME_MAIN: "your-cloudwatch-stream"
  LOG_GROUP_ASSOCIATE: "your-log-group-associate"
  STREAM_NAME_ASSOCIATE: "your-stream-name-associate"
  DJANGO_SECRET_KEY: "your-super-secret-key"
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "dGltZXNoZWV0cGFzc3dvcmQ="